version: "3.7"
services:
  db:
    image: postgres:14
    container_name: db_lumen
    ports:
      - "5433:5432"
    env_file:
      - .env-prod

  lumen:
    image: vadim2422/lumen:latest
    env_file:
      - .env-prod
    container_name: lumen_app
    environment:
      - TZ=Europe/Moscow
    command: sh -c  "sleep 5 && alembic upgrade head && python3 generate_data.py && gunicorn src.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 8888:8000
    tty: true
    depends_on:
      - db
